config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'registries#index', as: :home
  resources :registries
  resources :participants
  resources :coordinators do
    patch :enroll, on: :member
    get   :enroll, on: :member
    get   :export, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coordinator.rb
class Coordinator < User

  has_many :enrollment_informations, dependent: :destroy
  has_many :registries, through: :enrollment_informations
  has_many :participants, through: :enrollment_informations


  accepts_nested_attributes_for :enrollment_informations

  def self.to_csv
    attributes = %w{id email name phone_number gender date_of_birth participants}

    CSV.generate(headers: true) do |csv|
      csv << ['Id', 'Email', 'Name', 'Participants Name']

      all.includes(:participants).each do |coordinator|
        csv << [coordinator.id, coordinator.name, coordinator.email, coordinator.participants.pluck(:name).join(', ')]
      end
    end
  end
  
end

app/models/enrollment_information.rb
class EnrollmentInformation < ApplicationRecord
  CONTACT_METHODS = [:email, :phone]

  validates :registry_id, presence: true

  belongs_to :registry
  has_many :enrollment_participants, dependent: :destroy
  has_many :participants, through: :enrollment_participants

  before_validation :set_enrollment_date

  private

  def set_enrollment_date
    self.date_of_enrollment ||= Date.today
  end

end

app/models/enrollment_participant.rb
class EnrollmentParticipant < ApplicationRecord
  belongs_to :enrollment_information
  belongs_to :participant
end

app/models/participant.rb
class Participant < User
  has_many :enrollment_participants
  has_many :enrollment_informations, through: :enrollment_participants
  has_many :registries, through: :enrollment_informations
end

app/models/registry.rb
class Registry < ApplicationRecord

  enum status: {
    open: 0,
    closed: 1
  }

  validates :name, :status, presence: true

  has_many :registry_coordinators
  has_many :coordinators, through: :registry_coordinators

end

app/models/registry_coordinator.rb
class RegistryCoordinator < ApplicationRecord
  include RescueUniqueConstraint
  rescue_unique_constraint index: "index_registry_coordinators_on_registry_id_and_user_id", field: :register_id

  belongs_to :registry
  belongs_to :coordinator, foreign_key: :user_id

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  
  before_action :find_coordinator, only: [:update, :destroy, :edit, :enroll, :show]

  def index
  	@coordinators = Coordinator.all.page(params[:page]).per(params[:per] || 10)
  end

  def new
    @coordinator = Coordinator.new
  end

  def edit
  end

  def show
  end

  def create
    @coordinator = Coordinator.new(coordinators_params)

    respond_to do |format|
      if @coordinator.save
        format.html { redirect_to coordinators_path, notice: "Coordinator was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @coordinator.update(coordinators_params)
        format.html { redirect_to coordinators_path, notice: "Coordinator was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coordinator.destroy

    respond_to do |format|
      format.html { redirect_to coordinators_path, notice: "Coordinator was successfully destroyed." }
    end
  end

  def enroll
    if request.get?
      @coordinator.enrollment_informations.build if @coordinator.enrollment_informations.blank?
    else
      respond_to do |format|
        if @coordinator.update!(coordinators_params)
          format.html { redirect_to coordinators_path, notice: "Coordinator was successfully updated." }
        else
          format.html { render :enroll, status: :unprocessable_entity }
        end
      end
    end
  end

  def export
    @coordinators = Coordinator.all
    respond_to do |format|
      format.csv { send_data @coordinators.to_csv, filename: "Coordinators-#{Date.today}.csv" }
    end
  end

  private

  def find_coordinator
    @coordinator = Coordinator.includes(enrollment_informations: [:registry, :participants]).find(params[:id])
  end

  def coordinators_params
    params.required(:coordinator).permit(:id, :name, :email, :phone_number, :gender, :date_of_birth, enrollment_informations_attributes: [:registry_id, :method_of_contact, :remarks, participant_ids: []] )
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  
  before_action :find_participant, only: [:update, :destroy, :edit, :show]

  def index
    @participants = Participant.all.page(params[:page]).per(params[:per] || 10)
  end

  def new
    @participant = Participant.new
  end

  def edit
  end

  def show
  end

  def create
    @participant = Participant.new(participants_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to participants_path, notice: "Participant was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @participant.update!(participants_params)
        format.html { redirect_to participants_path, notice: "Participant was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_path, notice: "Participant was successfully destroyed." }
    end
  end

  private

  def find_participant
    @participant = Participant.find(params[:id])
  end

  def participants_params
    params.required(:participant).permit(:id, :name, :email, :phone_number, :gender, :date_of_birth, :type)
  end

end

app/controllers/registries_controller.rb
class RegistriesController < ApplicationController
  
  before_action :find_registry, only: [:update, :destroy, :edit, :show]

  def index
    @registries = Registry.all.page(params[:page]).per(params[:per] || 10)
  end

  def new
    @registry = Registry.new
  end

  def create
    @registry = Registry.new(registry_params)

    respond_to do |format|
      if @registry.save
        format.html { redirect_to registries_path, notice: "Registry was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @registry.update(registry_params)
        format.html { redirect_to registries_path, notice: "Registry was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @registry.destroy

    respond_to do |format|
      format.html { redirect_to registries_path, notice: "Registry was successfully destroyed." }
    end
  end

  def show
  end

  private

  def find_registry
    @registry = Registry.find(params[:id])
  end

  def registry_params
    params.required(:registry).permit(:id, :name, :location, :status, coordinator_ids: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coordinators/_form.html.slim
.centered-div
  = simple_form_for @coordinator, validate: true do |f|
    .row
      .col-sm-2
        | Name
      .col-sm-10
        = f.input :name, label: false
    .row
      .col-sm-2
        | Email
      .col-sm-10
        = f.input :email, label: false
    .row
      .col-sm-2
        | Phone Number
      .col-sm-10
        = f.input :phone_number, label: false
    .row
      .col-sm-2
        | Gender
      .col-sm-10
        = f.input :gender, as: :select, collection: ['Male', 'Female'], label: false
    .row
      .col-sm-2
        | Date of Birth
      .col-sm-10
        = f.input :date_of_birth, label: false, class: 'datepicker'
    .row
      .col-sm-12
        = f.submit 'Save', class: 'btn btn-primary'

app/views/coordinators/edit.html.slim
= render 'form'

app/views/coordinators/enroll.html.slim
.centered-div
  = simple_form_for @coordinator, url: enroll_coordinator_path(@coordinator) do |f|
    = f.fields_for :enrollment_informations do |ei|
      = ei.select  :registry_id, Registry.open.map{|r| [r.name, r.id]}, { prompt: 'Select Registry' }, { class: 'select2-input' }
      = ei.input   :method_of_contact, as: :select, collection: EnrollmentInformation::CONTACT_METHODS.map{|m| [m.to_s.titleize, m]}
      = ei.input   :remarks, as: :text
      = ei.select  :participant_ids, Participant.all.map{|a| [a.name, a.id]}, {prompt: 'Select Participants' }, { multiple: true, class: 'select2-input'}
    = f.submit 'Save', class: 'btn btn-primary'

app/views/coordinators/index.html.slim
.centered-div
  .row
    .col-sm-6
      h2
        | Coordinators
    .col-sm-6
      .pull-right
        = link_to 'Add New', new_coordinator_path, class: 'btn btn-primary mt20'
        span.pl10
          = link_to 'Export', export_coordinators_path({format: :csv}), class: 'btn btn-primary mt20', target: '_blank'
  table.table.table-striped
    thead
      tr
        th scope="col"
          | Id
        th scope="col"
          | Name
        th scope="col"
          | Email
        th scope="col"
          | Phone Number
        th scope="col"
          | Gender
        th scope="col"
          | Date of Birth
        th scope="col"
          | Actions
    tbody
      - @coordinators.each do |coordinator|
        tr
          td
            = coordinator.id
          td
            = coordinator.name
          td
            = coordinator.email
          td
            = coordinator.phone_number
          td
            = coordinator.gender
          td
            = coordinator.date_of_birth
          td
            = link_to 'Edit Coordinator', edit_coordinator_path(coordinator.id), class: 'btn btn-primary btn-sm'
            span.pl10
              = link_to 'Enroll to Registry', enroll_coordinator_path(coordinator), class: 'btn btn-primary btn-sm'
            span.pl10
              = link_to 'View', coordinator_path(coordinator), class: 'btn btn-primary btn-sm'

    tfoot
      tr
        td
          = paginate @coordinators

app/views/coordinators/new.html.slim
= render 'form'

app/views/coordinators/show.html.slim
.centered-div
  h2
    | Coordinator
  .row
    .col-sm-1
      label
        | Name
    .col-sm-11
      = @coordinator.name
  - @coordinator.enrollment_informations.each do |en_info|
    .row
      .col-sm-1
        label
          | Registy
      .col-sm-11
        = en_info.registry.name
    .row
      .col-sm-1
        h4
          | Participants:
    table.table.table-striped
      thead
        tr
          th
            | Name
          th
            | Email
          th
            | Date Of Birth
      tbody
        - en_info.participants.each do |participant|
          tr
            td
              = participant.name
            td
              = participant.email
            td
              = participant.date_of_birth

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssessmentApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Assessment App</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="active" >
            <%= link_to 'Registries', registries_path %>
          </li>
          <li>
             <%= link_to 'Coordinators', coordinators_path %>
          </li>
          <li>
            <%= link_to 'Participants', participants_path %>
          </li>
        </ul>
      </div>
    </nav>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participants/_form.html.slim
.centered-div
  = simple_form_for @participant, validate: true do |f|
    .row
      .col-sm-2
        | Name
      .col-sm-10
        = f.input :name, label: false
    .row
      .col-sm-2
        | Email
      .col-sm-10
        = f.input :email, label: false
    .row
      .col-sm-2
        | Phone Number
      .col-sm-10
        = f.input :phone_number, label: false
    .row
      .col-sm-2
        | Gender
      .col-sm-10
        = f.input :gender, as: :select, collection: ['Male', 'Female'], label: false
    .row
      .col-sm-2
        | Date of Birth
      .col-sm-10
        = f.input :date_of_birth, label: false, class: 'datepicker'
    .row
      .col-sm-12
        = f.submit 'Save', class: 'btn btn-primary'

app/views/participants/edit.html.slim
= render 'form'

app/views/participants/index.html.slim
.centered-div
  .row
    .col-sm-6
      h2
        | Participants
    .col-sm-6
      = link_to 'Add New', new_participant_path, class: 'btn btn-primary pull-right mt20'
  table class="table table-striped"
    thead
      tr
        th scope="col"
          | Id
        th scope="col"
          | Name
        th scope="col"
          | Email
        th scope="col"
          | Phone Number
        th scope="col"
          | Gender
        th scope="col"
          | Date of Birth
        th scope="col"
          | Actions
    tbody
      - @participants.each do |participant|
        tr
          td
            = participant.id
          td
            = participant.name
          td
            = participant.email
          td
            = participant.phone_number
          td
            = participant.gender
          td
            = participant.date_of_birth
          td
            = link_to 'Edit Participant', edit_participant_path(participant), class: 'btn btn-primary btn-sm'
            span.pl10
              = link_to 'View', participant_path(participant), class: 'btn btn-primary btn-sm'

    tfoot
      tr
        td
          = paginate @participants

app/views/participants/new.html.slim
= render 'form'

app/views/participants/show.html.slim
.centered-div
  h2
    | Participant
  .row
    .col-sm-1
      label
        | Name
    .col-sm-11
      = @participant.name
  .row
    .col-sm-1
      h4
        | Registy:
  table.table.table-striped
    thead
      tr
        th
          | Name
        th
          | Email
        th
          | Date Of Birth
    tbody
      - @participant.registries.each do |registry|
        tr
          td
            = registry.name
          td
            = registry.location
          td
            = registry.status

app/views/registries/_form.html.slim
.centered-div
  = simple_form_for @registry do |f|
    .row
      .col-sm-2
        | Name
      .col-sm-10
        = f.input :name, label: false
    .row
      .col-sm-2
        | Location
      .col-sm-10
        = f.input :location, label: false
    .row
      .col-sm-2
        | Status
      .col-sm-10
        = f.input :status, as: :select, collection: Registry.statuses.map{|k,v| [k.titleize, k]}, selected: f.object.status, label: false
    .row
      .col-sm-2
        | Select Coordinator
      .col-sm-10
        = f.select :coordinator_ids, Coordinator.all.map{|a| [a.name, a.id]}, {prompt: true}, { multiple: true, label: false, class: 'select2-input' }
    .row
      .col-sm-12
        = f.submit 'Save', class: 'btn btn-primary'

app/views/registries/edit.html.slim
.centered-div
  h4
    | Update Register
  = render 'form'

app/views/registries/index.html.slim
.centered-div
  .row
    .col-sm-6
      h2
        | Registries
    .col-sm-6
      = link_to 'Add New', new_registry_path, class: 'btn btn-primary pull-right mt20'
  table class="table table-striped "
    thead
      tr
        th scope="col"
          | Id
        th scope="col"
          | Name
        th scope="col"
          | Location
        th scope="col"
          | Status
        th scope="col"
          | Actions
    tbody
      - @registries.each do |registry|
        tr
          td
            = registry.id
          td
            = registry.name
          td
            = registry.location
          td
            = registry.status
          td
            = link_to 'Add Coordinator', edit_registry_path(registry.id), class: 'btn btn-primary btn-sm'
            span.pl10
              = link_to 'View', registry_path(registry), class: 'btn btn-primary btn-sm'

    tfoot
      tr
        td
          = paginate @registries

app/views/registries/new.html.slim
= render 'form'